import type { Metadata } from "next"
import { Martian_Mono } from "next/font/google"

import "../styles/globals.css"
import Providers from "./providers"
import { Layout } from "./customLayout"
import { Suspense } from "react"

const martianMono = Martian_Mono({
  variable: "--font-martian-mono",
  subsets: ["latin"],
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${martianMono.variable} antialiased`}>
        <Suspense>
          <Providers>
            <Layout>{children}</Layout>
          </Providers>
        </Suspense>
      </body>
    </html>
  )
}
