name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:

  using-github-secrets:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
    - uses: actions/checkout@v3
    - name: Create .env file
    - run: |
          touch .env
          echo "${{secrets.TEST_SECRETS}}" >> .env
    - name: Test printing your secret (Remove this step in production)
    - run: |
          cat .env
      
  build:
    needs: using-github-secrets

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.10.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: pm2 restart 0
